"""Python Data Analyst: deterministic pandas/numpy/scipy statistics over
SQL query results.

Dispatches on the Query Analyzer's `analysis_type` to compute descriptive
stats, group comparisons, trends, correlations, contribution breakdowns, or
anomalies. Deliberately LLM-free (like the SQL Validator/Executor): every
number handed to the future Insight Agent must be independently
reproducible from the SQL result set, not generated by a model.
"""
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats

ANOMALY_Z_THRESHOLD = 2.5


@dataclass
class PythonAnalysisResult:
    analysis_type: str
    summary: dict[str, Any] = field(default_factory=dict)
    table: list[dict[str, Any]] = field(default_factory=list)
    error: str | None = None


def analyze(
    rows: list[dict],
    analysis_type: str,
    metric: str | None = None,
    dimensions: list[str] | None = None,
) -> PythonAnalysisResult:
    """Runs the statistical analysis matching `analysis_type` over `rows`
    (the SQL Executor's result set). Never raises: malformed or unexpected
    data (an LLM-generated query can return anything) is reported back as
    an `error` on the result instead of crashing the graph.
    """
    if not rows:
        return PythonAnalysisResult(analysis_type=analysis_type, error="No rows to analyze.")

    df = _coerce_numeric_columns(pd.DataFrame(rows))
    dimensions = [d for d in (dimensions or []) if d in df.columns]
    handler = _HANDLERS.get(analysis_type, _descriptive)

    try:
        metric_col = _resolve_metric_column(df, metric)
        return handler(df, metric_col, dimensions)
    except _AnalysisError as e:
        return PythonAnalysisResult(analysis_type=analysis_type, error=str(e))


class _AnalysisError(Exception):
    """Raised for expected failure modes (no numeric column, no group column,
    ...) and turned into `PythonAnalysisResult.error` by `analyze()`."""


def _coerce_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    """SQLAlchemy/psycopg return PostgreSQL NUMERIC columns as `Decimal`,
    which pandas stores as dtype `object` — invisible to
    `select_dtypes(include="number")`. Convert any object column that
    converts to numeric losslessly (every non-null value parses), so
    money/quantity columns are recognized as metrics."""
    for col in df.columns:
        if df[col].dtype != object:
            continue
        converted = pd.to_numeric(df[col], errors="coerce")
        if converted.notna().sum() == df[col].notna().sum():
            df[col] = converted
    return df


def _resolve_metric_column(df: pd.DataFrame, metric: str | None) -> str:
    numeric_cols = list(df.select_dtypes(include="number").columns)
    if not numeric_cols:
        raise _AnalysisError("The query result has no numeric column to analyze.")

    if metric:
        for col in df.columns:
            if metric.lower().replace(" ", "_") in col.lower():
                if col in numeric_cols:
                    return col
    return numeric_cols[0]


def _descriptive(df: pd.DataFrame, metric_col: str, dimensions: list[str]) -> PythonAnalysisResult:
    series = df[metric_col].dropna()
    summary = {
        "metric": metric_col,
        "count": int(series.count()),
        "mean": float(series.mean()),
        "median": float(series.median()),
        "std": float(series.std()) if series.count() > 1 else 0.0,
        "min": float(series.min()),
        "max": float(series.max()),
        "sum": float(series.sum()),
    }
    return PythonAnalysisResult(analysis_type="descriptive", summary=summary)


def _group_comparison(df: pd.DataFrame, metric_col: str, dimensions: list[str]) -> PythonAnalysisResult:
    if not dimensions:
        raise _AnalysisError("Group comparison requires at least one dimension column in the result set.")

    group_col = dimensions[0]
    grouped = (
        df.groupby(group_col)[metric_col]
        .agg(["sum", "mean", "count"])
        .sort_values("sum", ascending=False)
        .reset_index()
    )
    table = [
        {"group": row[group_col], "sum": float(row["sum"]), "mean": float(row["mean"]), "count": int(row["count"])}
        for _, row in grouped.iterrows()
    ]
    summary = {
        "metric": metric_col,
        "grouped_by": group_col,
        "top_group": table[0]["group"] if table else None,
        "bottom_group": table[-1]["group"] if table else None,
    }
    return PythonAnalysisResult(analysis_type="comparison", summary=summary, table=table)


def _trend(df: pd.DataFrame, metric_col: str, dimensions: list[str]) -> PythonAnalysisResult:
    time_col = _find_time_column(df)
    if time_col is None:
        raise _AnalysisError("Trend analysis requires a date/period column in the result set.")

    ordered = df[[time_col, metric_col]].dropna().sort_values(time_col)
    if len(ordered) < 2:
        raise _AnalysisError("Trend analysis requires at least two data points.")

    x = np.arange(len(ordered), dtype=float)
    y = ordered[metric_col].to_numpy(dtype=float)
    regression = scipy_stats.linregress(x, y)

    first, last = float(y[0]), float(y[-1])
    pct_change = ((last - first) / first * 100) if first != 0 else None

    table = [
        {"period": str(row[time_col]), "value": float(row[metric_col])} for _, row in ordered.iterrows()
    ]
    summary = {
        "metric": metric_col,
        "time_column": time_col,
        "direction": "increasing" if regression.slope > 0 else "decreasing" if regression.slope < 0 else "flat",
        "slope": float(regression.slope),
        "r_squared": float(regression.rvalue**2),
        "first_value": first,
        "last_value": last,
        "pct_change": pct_change,
    }
    return PythonAnalysisResult(analysis_type="trend", summary=summary, table=table)


def _correlation(df: pd.DataFrame, metric_col: str, dimensions: list[str]) -> PythonAnalysisResult:
    numeric_df = df.select_dtypes(include="number").dropna()
    other_cols = [c for c in numeric_df.columns if c != metric_col]
    if not other_cols:
        raise _AnalysisError("Correlation requires at least two numeric columns in the result set.")

    table = []
    for col in other_cols:
        if numeric_df[metric_col].nunique() < 2 or numeric_df[col].nunique() < 2:
            continue
        r, p_value = scipy_stats.pearsonr(numeric_df[metric_col], numeric_df[col])
        table.append({"column": col, "correlation": float(r), "p_value": float(p_value)})

    table.sort(key=lambda row: abs(row["correlation"]), reverse=True)
    summary = {
        "metric": metric_col,
        "strongest_correlation": table[0] if table else None,
    }
    return PythonAnalysisResult(analysis_type="correlation", summary=summary, table=table)


def _anomaly_detection(df: pd.DataFrame, metric_col: str, dimensions: list[str]) -> PythonAnalysisResult:
    series = df[metric_col].dropna()
    if series.count() < 2 or series.std() == 0:
        return PythonAnalysisResult(
            analysis_type="anomaly_detection",
            summary={"metric": metric_col, "anomaly_count": 0},
        )

    z_scores = (series - series.mean()) / series.std()
    anomalies = df.loc[z_scores[z_scores.abs() > ANOMALY_Z_THRESHOLD].index]

    table = [{**row.to_dict(), "z_score": float(z_scores[idx])} for idx, row in anomalies.iterrows()]
    summary = {"metric": metric_col, "anomaly_count": len(table), "threshold_z_score": ANOMALY_Z_THRESHOLD}
    return PythonAnalysisResult(analysis_type="anomaly_detection", summary=summary, table=table)


def _contribution_analysis(df: pd.DataFrame, metric_col: str, dimensions: list[str]) -> PythonAnalysisResult:
    if not dimensions:
        raise _AnalysisError("Contribution analysis requires at least one dimension column in the result set.")

    group_col = dimensions[0]
    grouped = df.groupby(group_col)[metric_col].sum().sort_values(ascending=False)
    total = grouped.sum()
    if total == 0:
        raise _AnalysisError("Total is zero; contribution shares are undefined.")

    table = [
        {"group": group, "value": float(value), "share_pct": float(value / total * 100)}
        for group, value in grouped.items()
    ]
    summary = {
        "metric": metric_col,
        "grouped_by": group_col,
        "top_contributor": table[0]["group"] if table else None,
        "top_contributor_share_pct": table[0]["share_pct"] if table else None,
    }
    return PythonAnalysisResult(analysis_type="root_cause", summary=summary, table=table)


def _find_time_column(df: pd.DataFrame) -> str | None:
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            return col
    for col in df.columns:
        if any(hint in col.lower() for hint in ("date", "month", "period", "day", "year", "time")):
            return col
    return None


_HANDLERS = {
    "descriptive": _descriptive,
    "comparison": _group_comparison,
    "ranking": _group_comparison,
    "trend": _trend,
    "correlation": _correlation,
    "anomaly_detection": _anomaly_detection,
    "root_cause": _contribution_analysis,
}
