"""add document_id to rag_documents and uploaded_datasets table

Revision ID: 4f80aeee63d2
Revises: 1260a0ead861
Create Date: 2026-08-15 01:46:00.217863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f80aeee63d2'
down_revision: Union[str, None] = '1260a0ead861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=63), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.add_column('rag_documents', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rag_documents_document_id'), 'rag_documents', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_documents_document_id'), table_name='rag_documents')
    op.drop_column('rag_documents', 'document_id')
    op.drop_table('uploaded_datasets')
    # ### end Alembic commands ###
